import {
  pgTable,
  uuid,
  text,
  numeric,
  boolean,
  integer,
  jsonb,
  timestamp,
} from "drizzle-orm/pg-core";

export const clients = pgTable("clients", {
  id: uuid("id").primaryKey().defaultRandom(),
  parentName: text("parent_name").notNull(),
  childName: text("child_name").notNull().default(""),
  childAge: text("child_age").notNull().default(""),
  email: text("email").notNull().default(""),
  email2: text("email2").notNull().default(""),
  phone: text("phone").notNull().default(""),
  phone2: text("phone2").notNull().default(""),
  cin: text("cin").notNull().default(""),
  cinMother: text("cin_mother").notNull().default(""),
  fatherName: text("father_name").notNull().default(""),
  motherName: text("mother_name").notNull().default(""),
  professionFather: text("profession_father").notNull().default(""),
  professionMother: text("profession_mother").notNull().default(""),
  address: text("address").notNull().default(""),
  childNames: jsonb("child_names").notNull().default([]),
  subscribedFrais: jsonb("subscribed_frais").notNull().default([]),
  dob: text("dob").notNull().default(""),
  level: text("level").notNull().default(""),
  crmStage: text("crm_stage").notNull().default("nouveau"),
  paymentStatus: text("payment_status").notNull().default("impaye"),
  monthlyFee: numeric("monthly_fee").notNull().default("0"),
  debt: numeric("debt").notNull().default("0"),
  overdue: boolean("overdue").notNull().default(false),
  paymentDay: integer("payment_day").notNull().default(1),
  notes: text("notes").notNull().default(""),
  whatsappOptin: boolean("whatsapp_optin").notNull().default(true),
  transport: boolean("transport").notNull().default(false),
  cantine: boolean("cantine").notNull().default(false),
  garderie: boolean("garderie").notNull().default(false),
  activites: boolean("activites").notNull().default(false),
  fratrie: integer("fratrie").notNull().default(1),
  remise: numeric("remise").notNull().default("0"),
  subscribedServices: jsonb("subscribed_services").notNull().default([]),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
